fn main() -> Result<(), std::io::Error> {
    let aaa = 10;

    Ok(())
}