fn main() -> Result<(), std::io::Error> {
    print!("Hello");

    Ok(())
}